#!/bin/bash

for i in {01..20}
do
        ping rpi$i -w 3 > /dev/null
        if [ $? -eq 0 ]; then
                echo "rpi$i is alive"
        else
                echo "rpi$i is dead"
        fi
done
